= Enabling GC Logging
:slug: enabling-gc-logging
:zendesk-id: 204225303
:author: Dave Gordon
:neo4j-versions: 3.5, 4.0
:tags: logging,garbage collection, heap, memory, jvm
:category: operations

== What is Garbage collection and why enabling it?

A garbage collection event is a complete pause of the java application (ie: neo4j-server).

It can be identified in the debug.log as a `stop-the-world` event.

For example:

If you notice issues with them such as too many pauses, too long of a pause, pauses causing cluster re-election, etc,  you can enabling GC logging for easier integration with monitoring parsers.

Keep in mind the following regarding GC logging:

* GC log files are cleared out when the database is restarted
* They are crucial for the analysis of the Application Performance 
* It will add minor overhead
* You might consider enabling this option on your live environments

== Enabling GC logging

As indicated in the product documentation in https://neo4j.com/docs/operations-manual/3.5/reference/configuration-settings/#config_dbms.logs.gc.enabled[3.5] or https://neo4j.com/docs/operations-manual/current/reference/configuration-settings/#config_dbms.logs.gc.enabled[newer], you can uncomment the following line to enable it:

[source,properties]
----
#dbms.logs.gc.enabled=true
----

Save the file and restart your server.

===  GC log location

The log file will be written to the logs directory as specified
https://neo4j.com/docs/operations-manual/current/configuration/file-locations/[here] and named `gc.log.<#>`

== Additional options

You can review our operational manual (https://neo4j.com/docs/operations-manual/3.5/reference/configuration-settings/#config_dbms.logs.gc.rotation.keep_number[3.5] or https://neo4j.com/docs/operations-manual/reference/configuration-settings/#config_dbms.logs.gc.rotation.keep_number[newer]) for additional settings such as the number of rotated files or their size.

== dbms.gc.log.options changes

`dbms.gc.log.options` differs due to the upgrade from Java 8 to 11 in 4.0.x.

We recommend to leave this commented so neo4j starts with working settings in both versions.

You can review those differences in the table below.


.Differences between 3.5.x and 4.0.x
[opts=headers,cols="a,m"]
|===
|neo4j version | configuration value
|3.5.x | #dbms.logs.gc.options=-XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCApplicationStoppedTime -XX:+PrintPromotionFailure -XX:+PrintTenuringDistribution
|4.0.x | #dbms.logs.gc.options=-Xlog:gc*,safepoint,age*=trace
|===

