= How to Use the Debug Log Parser Script
:slug: how-to-use-the-debug-log-parser-script
:author: Shawn Tozeski
:neo4j-versions: 3.3, 3.4, 3.5
:tags: debug
:category: operations

For analysis of the Neo4j debug.log, read this guide for using the `debugInfo.sh` parser script.

== What is the this script?

The debug.log is quite verbose and contains a lot of useful information for understanding the health and behavior of a Neo4j server instance or cluster. To assist in enabling support teams to more quickly and efficiently understand if the Neo4j server is health or not, Neo4j Support has produced  `debugInfo.sh` script to parse a debug.log file into a condensed, usable summary of information. 

== How do I use it?

First, download the script and helper files link:https://drive.google.com/open?id=1Sdv_BXIUsCHcSbZpS1z-s2DWngah4mWP[here].

To run the `debugInfo.sh` script on Linux systems, follow these steps:
 
=== As the neo4j user:
 
1. Copy the `debugInfo.sh` script and the `debugLogErrorsFile.neo4j` and `debugLogExcludeFile.neo4j` files to `$NEO4J_HOME/logs`

2. Review and modify the script User variables as required.

3. The default log location is the working directory where the script is run from. The default output file is called `debugInfo.txt`. 

4. Run `chmod 750 debugInfo.sh` to set execute permissions on the script.

5. Script usage:

[source,shell]
----
  $ ./debugInfo.sh debug.log
----

NOTE 1: The `debugInfo.sh` script will accept one input, which is the name of the Neo4j debug log to process.

NOTE 2: The `debugLogErrorsFile.neo4j` file is used to parse specific error values in the debug log. This file can be modified as required.
        The `debugLogExcludeFile.neo4j` file is used to exclude specific error values from the debug log error parsing. This file can be modified as required.

NOTE 3: The `debugInfo.sh` script will output results to the screen and also to the default output file called `debugInfo.txt` in the working directory.

=== To run the script from an alternative location, just provide the full path to the debug.log to analyze:

[source,shell]
----
  $ pwd
  /home/neo4j

  $ ls -la 
  total 40
  drwxrwxr-x   2 neo4j neo4j   112 Dec 19 13:23 .
  drwx------. 13 neo4j neo4j  4096 Dec 13 17:01 ..
  -rwx------   1 neo4j neo4j 17521 Dec 13 17:04 debugInfo.sh
  -rw-rw-r--   1 neo4j neo4j   427 Dec 13 16:47 debugLogErrorsFile.neo4j
  -rw-rw-r--   1 neo4j neo4j  1671 Dec 13 16:51 debugLogExcludeFile.neo4j

  $ ./debugInfo.sh debug.log $NEO4J_HOME/logs/debug.log
----

NOTE 1: The script will parse the debug.log from the location provided and output results to the screen and also to the default output file called `debugInfo.txt` in the working directory.
