= How to specify a separate debug.log for the backup process?
:slug: specify-separate-debug-log-for-backup
:author: Rohan Kharwar 
:neo4j-versions: 3.2,3.3,3.4,3.5
:tags: backup, configuration, neo4j.conf, debug.log 
:category: operations

When running `neo4j-admin backup` on a running Neo4j instance the backup logs are also written into the existing Neo4j instance `debug.log` and can get confusing as to which line items in the debug.log is part of backup process and those that are from running Neo4j instance. 
Hence we recommend having a separate directory where backup `debug.log` are written. 

Here is how to achieve this. 

Set the environment variable `NEO4J_CONF` to point to the new `neo4j.conf` that you setup for the backup process. 
Ideally you can copy the `neo4j.conf` file with the default settings and place it in the folder mentioned in `NEO4J_CONF`.

[source,shell]
----
export NEO4J_CONF=/Users/Documents/backup/
echo $NEO4J_CONF
# /Users/Documents/backup/
----

In the neo4j.conf file set the `dbms.directories.logs` to point to the backup logs folder. 

[source,conf]
----
dbms.directories.logs=/Users/Documents/backup/logs
----

Then run the backup as 

[source,shell]
----
./neo4j-admin backup --backup-dir=/Users/Documents/backup --name=graph.db.backup
----

Debug.log for the backup process should be present in the following folder specified `/Users/Documents/backup/logs`.
