= This is a Template
// CHANGE THIS, REMOVE COMMENTS BEFORE MERGE
// ANY SLUG CHANGES WILL CAUSE POSTS TO BE RE-CREATED, BREAKING EXISTING LINKS
:slug: this-is-a-template
:author: Your Name
:twitter: @your-twitter
// relevant versions
:neo4j-versions: 2.3, 3.0
// see taxonomy in readme, remove this comment
:tags: logging, server
// category see https://github.com/neo4j-documentation/knowledge-base/blob/master/kb-categories.txt
:category: cypher

Intro text.

Refer to a  `path/to/file`.

[source,cypher]
----
MATCH (:Person)-[:KNOWS]->(p)
RETURN p
----

Raw output:

....
2020-10-20 15:14:13.120+0000 INFO [a.b.c.Something] Some log
....

Open a terminal and run:

[source,shell]
$ brew install openssl

Once installed, run `openssl version -a`:

[source,shell,role=noheader]
----
$ openssl version -a
OpenSSL 1.0.2o  27 Mar 2018
....
----

IMPORTANT: Do not forget to add `role=noheader` when the source block contains the command, and the expected output.

The command format is:

[source,shell,role=nocopy]
----
$ nc -v <hostname> 5000
----

NOTE: Use `role=nocopy` to disable the "Copy to Clipboard" button.
This role is particularly useful when the command contains a placeholder because we don't want the user to blindly copy and paste the command.

Add the following to [.file]_neo4j.conf_:

[source,properties]
----
causal_clustering.ssl_policy=cluster
dbms.ssl.policy.cluster.ciphers=TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
dbms.ssl.policy.cluster.client_auth=REQUIRE
----

== Another Section

Some bullet points:

* One
* Two

// single line comment

. First
. Second

////
Multiline comment
////

NOTE: An admonition paragraph draws the reader's attention to auxiliary information.
Its purpose is determined by the label at the beginning of the paragraph.

Here are the other built-in admonition types:

TIP: Pro tip...

IMPORTANT: Don't forget...

WARNING: Watch out for...

CAUTION: Ensure that...
