= Enabling GC Logging
:slug: enabling-gc-logging
:zendesk-id: 204225303
:author: Dave Gordon
:neo4j-versions: 2.1,2.2,2.3,3.0,3.1,3.2,3.3,3.4,3.5
:tags: logging,garbage collection, heap, memory, jvm
:category: operations

If you are having issues with Garbage Collection (too many pauses, too long of a pause, pauses causing cluster re-election, etc),  you should look at enabling GC logging.

Keep in mind the following regarding GC logging:

* GC log files are cleared out when the database is restarted
* They are crucial for the analysis of the Application Performance 
* It will add minor overhead
* You might consider enabling this option on your live environments

== For Neo4j 2.x releases
Uncomment these lines in `conf/neo4j-wrapper.conf`:

[source,conf]
----
#wrapper.java.additional=-Xloggc:data/log/neo4j-gc.log
#wrapper.java.additional=-XX:+PrintGCDetails
#wrapper.java.additional=-XX:+PrintGCDateStamps
#wrapper.java.additional=-XX:+PrintGCApplicationStoppedTime
#wrapper.java.additional=-XX:+PrintTenuringDistribution
----

And add this line:

[source,conf]
----
wrapper.java.additional=-XX:+PrintGCCause
----

The log file will be written to: data/log/neo4j-gc.log

== For Neo4j 3.x releases
Uncomment these lines below in `conf/neo4j.conf` that are prefaced by # dbms.:

[source,conf]
----
# To enable GC Logging, uncomment this line
# dbms.logs.gc.enabled=true

# GC Logging Options
# see http://docs.oracle.com/cd/E19957-01/819-0084-10/pt_tuningjava.html#wp57013 for more information.
#dbms.logs.gc.options=-XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCApplicationStoppedTime -XX:+PrintPromotionFailure -XX:+PrintTenuringDistribution

# Number of GC logs to keep.
# dbms.logs.gc.rotation.keep_number=5

# Size of each GC log that is kept.
# dbms.logs.gc.rotation.size=20m
---- 

The log file will be written to the logs directory as specified by
https://neo4j.com/docs/operations-manual/current/configuration/file-locations/[here] and named `gc.log.<#>`

Save the file and restart your server.
