= Tuning GC algorithms
:slug: tuning-gc-algorithms
:author: Jeremie Phoulchand
:neo4j-versions: 3.4, 3.5
:tags: configuration
:category: performance

== Introduction

There are several Garbage Collection algorithms available and the list is expanding.
We will not review all of them but focus on the G1GC and two new ones.

== G1GC

This is the default GC algorithm since Java 9. This is the one used for internal testing.
It is available in every implementation.

== Shenandoah

This is an experimental feature available in some releases of OpenJDK on Linux only. Especially, the Red Hat one.
It allows you to have pauseless GCs (<10 ms) but at the expense of an higher CPU usage (20% additional CPU runtime usage).

WARNING: Please note that we do NOT test those algorithms therefore we will NOT be able to emit a recommendation.
Customers are free to test it on a lower environment and choose the one that suits them the best.

https://wiki.openjdk.java.net/display/shenandoah/Main

== C4 Azul

This version had its own proprietary pauseless algorithm which is supported.
This is a *paid* algorithm so you might need to get a licence first.

https://www.azul.com/resources/azul-technology/azul-c4-garbage-collector/

WARNING: Please note that we do NOT test those algorithms therefore we will NOT be able to emit a recommendation.
Customers are free to test it on a lower environment and choose the one that suits them the best.
