name: Publish

on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install dependencies
        run: |
          npm ci
      - name: Lint
        run: |
          FORCE_COLOR=1 npm run lint
      - name: Annotate
        uses: yuzutech/annotations-action@v0.2.0
        with:
          title: 'report'
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          input: './annotations.json'
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Publish Zendesk
        run: |
          ./gradlew zenDeskUpload -Pzendesk-email="${ZENDESK_EMAIL}" -Pzendesk-apitoken="${ZENDESK_APITOKEN}" -Pstage=production
        env:
          ZENDESK_EMAIL: ${{ secrets.ZENDESK_EMAIL }}
          ZENDESK_APITOKEN: ${{ secrets.ZENDESK_APITOKEN }}
